version: '3'
services:
  mongodb:
    image: bitnami/mongodb:latest
    env_file:
      - .env.mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
