version: '3'
services:
  postgresql:
    image: bitnami/postgresql:latest
    env_file:
      - .env.postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
