filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*
    tags: ["nginx"]
    json:
      keys_under_root: true
      add_error_key: true

  - type: log
    enabled: true
    paths:
      - /var/log/ugc_service/*
    tags: ["ugc_service"]
    json:
      keys_under_root: true
      add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash:5045"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
